import { ProgramPlan } from '@coachg/types';
import { AiClient } from './client';
import { buildSafeProgramContext, validateExplanation } from './guardrails';

const SYSTEM_PROMPT = `You are an expert strength & conditioning coach writing for a premium coaching report.
You will be given a training program that has ALREADY been generated by a deterministic engine.
Your ONLY job is to explain the RATIONALE in a motivating, professional coaching voice:
- WHY the program is structured this way (periodization, phases, deloads).
- HOW the athlete should approach each phase.
- Key focus cues.

STRICT RULES:
- Do NOT invent or suggest any exercises that are not already in the program.
- Do NOT change sets, reps, loads, or rest. The numbers are fixed.
- Do NOT give medical advice.
Write 3-5 concise paragraphs.`;

/**
 * Generate an AI explanation for a program. ALWAYS returns text — if AI is
 * disabled or fails, it falls back to a deterministic templated explanation so
 * the program is never blocked on the AI layer.
 */
export async function explainProgram(ai: AiClient, program: ProgramPlan): Promise<string> {
  if (!ai.isEnabled()) {
    return templatedExplanation(program);
  }
  try {
    const context = buildSafeProgramContext(program);
    const raw = await ai.complete(SYSTEM_PROMPT, context);
    const result = validateExplanation(raw, program);
    return result.text || templatedExplanation(program);
  } catch {
    return templatedExplanation(program);
  }
}

/** Deterministic fallback — guarantees a valid explanation without the AI. */
export function templatedExplanation(program: ProgramPlan): string {
  const deloads = program.weeks.filter((w) => w.isDeload).length;
  return [
    `This ${program.durationWeeks}-week ${program.periodization.toLowerCase()} program trains ${program.daysPerWeek} days per week, progressing systematically toward your goal.`,
    `The plan applies ${program.periodization.toLowerCase()} periodization so that volume and intensity shift across the block, driving adaptation while managing fatigue. ${deloads > 0 ? `It includes ${deloads} planned deload week(s) to consolidate gains and reduce injury risk.` : ''}`,
    `Each session follows a structured warm-up, primary strength work, and accessory volume selected specifically for your equipment, experience level, and any movement restrictions on file.`,
    `Focus on executing every rep with quality, applying the progression rules, and logging your sessions so your coach can fine-tune the plan over time.`,
  ].join('\n\n');
}
