import { Sport } from '@coachg/types';

/**
 * Sport Performance Engine (Module 7).
 *
 * Provides deterministic, sport-specific conditioning/qualities blocks that are
 * appended to a training day's `conditioning` section. These are coach-grade
 * protocols selected by rule — not generated by AI.
 */
export interface SportProtocol {
  /** Athletic qualities this sport prioritises (drives exercise sportTransferTags). */
  qualities: string[];
  /** Concrete conditioning/skill blocks to append to sessions. */
  blocks: string[];
}

const PROTOCOLS: Record<Sport, SportProtocol> = {
  [Sport.NONE]: {
    qualities: [],
    blocks: [],
  },
  [Sport.FOOTBALL]: {
    qualities: [
      'sprint',
      'acceleration',
      'max-velocity',
      'agility',
      'change-of-direction',
      'plyometric',
      'hamstring-prevention',
    ],
    blocks: [
      'Acceleration: 6 x 10–20m sprints, full recovery',
      'Max velocity: 4 x 30–40m flying runs',
      'Change of direction: 5-10-5 pro agility x6',
      'Nordic hamstring curls 3 x 5 (eccentric focus)',
    ],
  },
  [Sport.BASKETBALL]: {
    qualities: ['vertical-jump', 'reactive-strength', 'agility', 'plyometric'],
    blocks: [
      'Reactive strength: depth jumps 4 x 4 (short ground contact)',
      'Approach jumps 5 x 3 to a target',
      'Lateral agility ladder + closeouts 3 rounds',
    ],
  },
  [Sport.VOLLEYBALL]: {
    qualities: ['vertical-jump', 'reactive-strength', 'shoulder-health'],
    blocks: [
      'Approach jump technique 5 x 3',
      'Band external rotations + scap work 3 x 12',
      'Depth-to-approach jumps 4 x 3',
    ],
  },
  [Sport.COMBAT]: {
    qualities: ['strength-endurance', 'power', 'conditioning', 'rotational-power'],
    blocks: [
      'Medicine-ball rotational throws 4 x 5/side',
      'Strength-endurance circuit 3 rounds (carries, KB swings, push-ups)',
      'Anaerobic conditioning: 6 x 60s hard / 60s easy',
    ],
  },
  [Sport.RUNNING]: {
    qualities: ['aerobic', 'running-economy', 'speed', 'single-leg-stability'],
    blocks: [
      'Aerobic base: Zone-2 run 30–45 min',
      'Strides: 6 x 20s relaxed fast running',
      'Single-leg stability: 3 x 8/side',
    ],
  },
};

export function getSportProtocol(sport: Sport): SportProtocol {
  return PROTOCOLS[sport] ?? PROTOCOLS[Sport.NONE];
}
