apiVersion: v1
kind: ConfigMap
metadata:
  name: coachg-config
  namespace: coachg
data:
  NODE_ENV: 'production'
  BACKEND_PORT: '4000'
  FRONTEND_PORT: '3000'
  AUTH_PROVIDER: 'keycloak'
  S3_REGION: 'ir-thr-at1'
  S3_FORCE_PATH_STYLE: 'true'
  PROMETHEUS_ENABLED: 'true'
  LOG_LEVEL: 'info'
