apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coachg-ingress
  namespace: coachg
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: '25m'
spec:
  ingressClassName: nginx
  tls:
    - hosts: [coachg.example.com]
      secretName: coachg-tls
  rules:
    - host: coachg.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port: { number: 4000 }
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port: { number: 5000 }
